# 以下の内容を.mise.local.tomlに記載することでenvを上書きしてください。

[env]
# Terraform Backend Configuration
TF_BACKEND_S3_BUCKET = "REPLACE_WITH_YOUR_S3_BUCKET_NAME"
TF_BACKEND_DYNAMODB_TABLE = "REPLACE_WITH_YOUR_DYNAMODB_TABLE_NAME"
TF_BACKEND_REGION = "REPLACE_WITH_YOUR_AWS_REGION(ex. ap-northeast-1)"
GH_USER = "REPLACE_WITH_YOUR_GITHUB_USER(ex. take-takashi)"
GH_REPO = "REPLACE_WITH_YOUR_GITHUB_REPO(ex. try-aws-lambda-web-adapter)"
